#!/bin/sh /etc/rc.common
# GPIO startup script
 
START=1
STOP=2
 
start() {        
        /atom/gpio/gpio_interface /atom/gpio/config/gpio_config.xml &
}                 
 
stop() {          
        killall gpio_interface
}

boot() {
        /atom/gpio/gpio_interface /atom/gpio/config/gpio_config.xml &
}
