#!/bin/sh /etc/rc.common
# GPIO startup script

START=1
STOP=2

start() {
        /Atlants/gpio/gpio_interface /Atlants/gpio/config/gpio_config.xml &
}

stop() {
        killall gpio_interface
}

boot() {
        /Atlants/gpio/gpio_interface /Atlants/gpio/config/gpio_config.xml &
}
