#!/bin/sh /etc/rc.common
# atxPi startup script
 
START=1
STOP=2
 
start() {        
        sh /etc/shutdowncheck &
}                 
 
stop() {          
       echo "shutdown requires no command for atxPi"
}

boot() {
        sh /etc/shutdowncheck &
}
